global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tinyurl
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]
        labels:
          service: tinyurl

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
