package base62

import (
	"errors"
	"fmt"
	"testing"
)

func TestEncodeKnownVectors(t *testing.T) {
	cases := []struct {
		id   uint64
		code string
	}{
		{0, "100000"}, // smallest ID is shifted to 62^5
		{1, "100001"},
		{42, "10000G"}, // digit value 42 in [0-9a-zA-Z] is 'G'
	}
	for _, tc := range cases {
		got, err := Encode(tc.id)
		if err != nil {
			t.Fatalf("Encode(%d) unexpected error: %v", tc.id, err)
		}
		if got != tc.code {
			t.Errorf("Encode(%d) = %q, want %q", tc.id, got, tc.code)
		}
	}
}

func TestEncodeAlwaysSixChars(t *testing.T) {
	for _, id := range []uint64{0, 1, 61, 62, 63, 916132831, MinID, MaxID} {
		code, err := Encode(id)
		if err != nil {
			t.Fatalf("Encode(%d) error: %v", id, err)
		}
		if len(code) != CodeLength {
			t.Fatalf("Encode(%d) = %q has length %d, want %d", id, code, len(code), CodeLength)
		}
	}
}

func TestEncodeOverflow(t *testing.T) {
	if _, err := Encode(MaxID + 1); !errors.Is(err, ErrOverflow) {
		t.Fatalf("Encode(MaxID+1) error = %v, want ErrOverflow", err)
	}
}

func TestCapacity(t *testing.T) {
	// Full 6-char space: 62^6 = 56,800,235,584; usable IDs after the offset:
	if got := MaxID + 1; got != 55_884_102_752 {
		t.Errorf("usable code count = %d, want 55884102752", got)
	}
	if space := MaxID + MinID + 1; space != 56_800_235_584 {
		t.Errorf("6-char space = %d, want 56800235584", space)
	}
}

func TestRoundTripAndUnique(t *testing.T) {
	// Note: codes are numerically monotonic but not ASCII-lexicographic because
	// the alphabet orders lowercase (10..35) before uppercase (36..61), so we
	// assert injectivity via a duplicate check instead of string ordering.
	const n = 2_000_000
	seen := make(map[string]uint64, n)
	for id := uint64(0); id < n; id++ {
		code, err := Encode(id)
		if err != nil {
			t.Fatalf("Encode(%d) error: %v", id, err)
		}
		decoded, err := Decode(code)
		if err != nil {
			t.Fatalf("Decode(%q) error: %v", code, err)
		}
		if decoded != id {
			t.Fatalf("round-trip mismatch for %d: got %d (code %s)", id, decoded, code)
		}
		if other, dup := seen[code]; dup {
			t.Fatalf("code %q generated by both id %d and id %d", code, other, id)
		}
		seen[code] = id
	}
}

func TestDecodeInvalid(t *testing.T) {
	bad := []string{"", "abc", "10000", "1000001", "100!00", "000000", "------"}
	for _, code := range bad {
		if _, err := Decode(code); !errors.Is(err, ErrInvalidCode) {
			t.Errorf("Decode(%q) error = %v, want ErrInvalidCode", code, err)
		}
	}
}

func BenchmarkEncode(b *testing.B) {
	for i := 0; i < b.N; i++ {
		if _, err := Encode(uint64(i)); err != nil {
			b.Fatal(err)
		}
	}
}

func ExampleEncode() {
	code, _ := Encode(1)
	fmt.Println(code)
	// Output: 100001
}
